// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  docs: [
    "intro",
    {
      type: "category",
      label: "Instalación y Configuración",
      items: [
        "instalacion/requisitos",
        "instalacion/instalacion-usuario",
        "instalacion/configuracion",
      ],
    },
    {
      type: "category",
      label: "Guía de Usuario",
      items: [
        "guia-usuario/interfaz",
        "guia-usuario/busqueda-rutas",
        "guia-usuario/visualizacion",
        "guia-usuario/notificaciones",
        "guia-usuario/planificacion",
      ],
    },
    {
      type: "category",
      label: "Arquitectura del Sistema",
      items: [
        "arquitectura/vision-general",
        "arquitectura/componentes",
        "arquitectura/tecnologias",
        "arquitectura/flujo-datos",
      ],
    },
    {
      type: "category",
      label: "APIs y Servicios",
      items: ["api/autenticacion", "api/endpoints", "api/ejemplos"],
    },
    "faq",
    "roadmap",
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
